version: "3.8"  # optional since v1.27.0

services:

  react:
    image: react
    build:
      context: ./react
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 5000:5000


  rasa_action:
    image: rasa_action
    build:
      context: .
      dockerfile: ./rasa/actions/Dockerfile
    ports:
      - 5055:5055
    networks:
      - mynet

  rasa_server:
    image: rasa_server
    build:
      context: ./rasa/server
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 5005:5005
    networks:
      - mynet


networks:
  mynet:


