version: "3.3"  # optional since v1.27.0

services:
  rasa_action:
    image: rasa_action
    build:
      context: .
      dockerfile: ./Dockerfile_action
    ports:
      - 5055:5055
    networks:
      - mynet
  rasa_server:
    image: rasa_server
    build:
      context: .
      dockerfile: ./Dockerfile_server
    env_file:
      - .env
    ports:
      - 5005:5005
    networks:
      - mynet


networks:
  mynet:


