# set base image (host OS)
FROM python:3.8

# set the working directory in the container
WORKDIR /code
RUN wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip and && unzip ngrok-stable-linux-amd64.zip
RUN ./ngrok authtoken ${AUTH_TOKEN}

CMD ["./ngrok", "http", "5005"]

